a_main:
    pattern: /
    defaults: { _controller: EduEleraningBundle:Admin:admin}

adduniversity:
    pattern: /addmanager
    defaults: { _controller: EduEleraningBundle:Admin:adduniversity}

showuniversities:
    pattern: /showuniversity
    defaults: { _controller: EduEleraningBundle:Admin:showuniversity}

extensionuniversity:
    pattern: /extensionuniversity
    defaults: { _controller: EduEleraningBundle:Admin:extensionuniversity}