financial:
    pattern:  /
    defaults: { _controller: "EduEleraningBundle:financial:index" }

financial_show:
    pattern:  /{id}/show
    defaults: { _controller: "EduEleraningBundle:financial:show" }

financial_new:
    pattern:  /new
    defaults: { _controller: "EduEleraningBundle:financial:new" }

financial_create:
    pattern:  /create
    defaults: { _controller: "EduEleraningBundle:financial:create" }
    requirements: { _method: post }

financial_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EduEleraningBundle:financial:edit" }

financial_update:
    pattern:  /{id}/update
    defaults: { _controller: "EduEleraningBundle:financial:update" }
    requirements: { _method: post|put }

financial_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EduEleraningBundle:financial:delete" }
    requirements: { _method: post|delete }
