grouplesson:
    pattern:  /
    defaults: { _controller: "EduEleraningBundle:grouplesson:index" }

grouplesson_show:
    pattern:  /{id}/show
    defaults: { _controller: "EduEleraningBundle:grouplesson:show" }

grouplesson_new:
    pattern:  /new
    defaults: { _controller: "EduEleraningBundle:grouplesson:new" }

grouplesson_create:
    pattern:  /create
    defaults: { _controller: "EduEleraningBundle:grouplesson:create" }
    requirements: { _method: post }

grouplesson_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EduEleraningBundle:grouplesson:edit" }

grouplesson_update:
    pattern:  /{id}/update
    defaults: { _controller: "EduEleraningBundle:grouplesson:update" }
    requirements: { _method: post|put }

grouplesson_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EduEleraningBundle:grouplesson:delete" }
    requirements: { _method: post|delete }
