lesson:
    pattern:  /
    defaults: { _controller: "EduEleraningBundle:lesson:index" }

lesson_show:
    pattern:  /{id}/show
    defaults: { _controller: "EduEleraningBundle:lesson:show" }

lesson_new:
    pattern:  /new
    defaults: { _controller: "EduEleraningBundle:lesson:new" }

lesson_create:
    pattern:  /create
    defaults: { _controller: "EduEleraningBundle:lesson:create" }
    requirements: { _method: post }

lesson_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EduEleraningBundle:lesson:edit" }

lesson_update:
    pattern:  /{id}/update
    defaults: { _controller: "EduEleraningBundle:lesson:update" }
    requirements: { _method: post|put }

lesson_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EduEleraningBundle:lesson:delete" }
    requirements: { _method: post|delete }
