memo:
    pattern:  /
    defaults: { _controller: "EduEleraningBundle:memo:index" }

memo_show:
    pattern:  /{id}/show
    defaults: { _controller: "EduEleraningBundle:memo:show" }

memo_new:
    pattern:  /new
    defaults: { _controller: "EduEleraningBundle:memo:new" }

memo_create:
    pattern:  /create
    defaults: { _controller: "EduEleraningBundle:memo:create" }
    requirements: { _method: post }

memo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EduEleraningBundle:memo:edit" }

memo_update:
    pattern:  /{id}/update
    defaults: { _controller: "EduEleraningBundle:memo:update" }
    requirements: { _method: post|put }

memo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EduEleraningBundle:memo:delete" }
    requirements: { _method: post|delete }
