post:
    pattern:  /
    defaults: { _controller: "EduEleraningBundle:post:index" }

post_show:
    pattern:  /{id}/show
    defaults: { _controller: "EduEleraningBundle:post:show" }

post_new:
    pattern:  /new
    defaults: { _controller: "EduEleraningBundle:post:new" }

post_create:
    pattern:  /create
    defaults: { _controller: "EduEleraningBundle:post:create" }
    requirements: { _method: post }

post_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EduEleraningBundle:post:edit" }

post_update:
    pattern:  /{id}/update
    defaults: { _controller: "EduEleraningBundle:post:update" }
    requirements: { _method: post|put }

post_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EduEleraningBundle:post:delete" }
    requirements: { _method: post|delete }
