university:
    pattern:  /
    defaults: { _controller: "EduEleraningBundle:university:index" }

university_show:
    pattern:  /{id}/show
    defaults: { _controller: "EduEleraningBundle:university:show" }

university_new:
    pattern:  /new
    defaults: { _controller: "EduEleraningBundle:university:new" }

university_create:
    pattern:  /create
    defaults: { _controller: "EduEleraningBundle:university:create" }
    requirements: { _method: post }

university_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EduEleraningBundle:university:edit" }

university_update:
    pattern:  /{id}/update
    defaults: { _controller: "EduEleraningBundle:university:update" }
    requirements: { _method: post|put }

university_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EduEleraningBundle:university:delete" }
    requirements: { _method: post|delete }
