user:
    pattern:  /
    defaults: { _controller: "EduEleraningBundle:user:index" }

user_show:
    pattern:  /{id}/show
    defaults: { _controller: "EduEleraningBundle:user:show" }

user_new:
    pattern:  /new
    defaults: { _controller: "EduEleraningBundle:user:new" }

user_create:
    pattern:  /create
    defaults: { _controller: "EduEleraningBundle:user:create" }
    requirements: { _method: post }

user_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EduEleraningBundle:user:edit" }

user_update:
    pattern:  /{id}/update
    defaults: { _controller: "EduEleraningBundle:user:update" }
    requirements: { _method: post|put }

user_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EduEleraningBundle:user:delete" }
    requirements: { _method: post|delete }
