parameters:
#    edu_eleraning.example.class: Edu\EleraningBundle\Example

services:
#    edu_eleraning.example:
#        class: %edu_eleraning.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    authentication_handler:
                class: Edu\EleraningBundle\Handler\AuthenticationHandler
                arguments: [@router, @security.context]

    edu_user.registration.form.type:
            class: Edu\EleraningBundle\Form\Type\RegistrationFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: edu_user_registration }

    family_tree.fos_events:
        class: Edu\EleraningBundle\Handler\FOSListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
